--SISC Assessment Payment Details--

IF EXISTS(SELECT NAME FROM sysobjects
WHERE NAME=N'SISC10400'
AND TYPE='U')
DROP TABLE SISC10400
GO

CREATE TABLE SISC10400
(
[SOPTYPE] SMALLINT NOT NULL,
[ASSESSNO] CHAR(21) NOT NULL,
[DUEDATE] SMALLDATETIME NOT NULL,
[AMOUNT] NUMERIC(19,5) NOT NULL
)

GO

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SISC10400 TO DYNGRP;

GO