--SISC Assessment Line--

IF EXISTS(SELECT NAME FROM sysobjects
WHERE NAME=N'SISC10200'
AND TYPE='U')
DROP TABLE SISC10200
GO

CREATE TABLE SISC10200
(
[SOPTYPE] SMALLINT NOT NULL,
[ASSESSNO] CHAR(21) NOT NULL,
[LNITMSEQ] INT NOT NULL,
[ITEMNMBR] CHAR(31) NOT NULL,
[ITEMDESC] CHAR(101) NOT NULL,
[UOFM] CHAR(9) NOT NULL,
[QUANTITY] NUMERIC(19,5) NOT NULL,
[UNITPRCE] NUMERIC(19,5) NOT NULL,
[MARKDOWN] NUMERIC(19,5) NOT NULL,
[EXTNDPRC] NUMERIC(19,5) NOT NULL,
PRIMARY KEY (SOPTYPE, ASSESSNO, LNITMSEQ, ITEMNMBR)
)

GO

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SISC10200 TO DYNGRP;

GO