--SISC Assessment Discount Line--

IF EXISTS(SELECT NAME FROM sysobjects
WHERE NAME=N'SISC10300'
AND TYPE='U')
DROP TABLE SISC10300
GO

CREATE TABLE SISC10300
(
[SOPTYPE] SMALLINT NOT NULL,
[ASSESSNO] CHAR(21) NOT NULL,
[LNITMSEQ] INT NOT NULL,
[DISCNTID] CHAR(15) NOT NULL,
[PERCENT] NUMERIC(19, 5) NOT NULL,
[DISCAMNT] NUMERIC(19,5) NOT NULL,
[APPLIED] CHAR(50) NOT NULL,

PRIMARY KEY (SOPTYPE, ASSESSNO,  DISCNTID)
)

GO

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SISC10300 TO DYNGRP;

GO