--SISC Assessment--

IF EXISTS(SELECT NAME FROM sysobjects
WHERE NAME=N'SISC10100'
AND TYPE='U')
DROP TABLE SISC10100
GO

CREATE TABLE SISC10100
(
[ASSESSNO] CHAR(21) NOT NULL,
[SOPTYPE] SMALLINT NOT NULL,
[CUSTNMBR] CHAR(15) NOT NULL FOREIGN KEY REFERENCES RM00101(CUSTNMBR),
[CUSTNAME] CHAR(65) NOT NULL,
[LEVEL] CHAR(11) NOT NULL,
[GRADELVL] CHAR(255) NOT NULL,
[CURNCYID] CHAR(15) NOT NULL,
[BACHNUMB] CHAR(15) NOT NULL,
[DOCDATE] DATETIME NOT NULL,
[PLAN] CHAR(6) NOT NULL,
[SCHLYRFR] SMALLINT NOT NULL,
[SCHLYRTO] SMALLINT NOT NULL,
[TOTLFEES] NUMERIC(19,5) NOT NULL,
[TOTLDISC] NUMERIC (19,5) NOT NULL,
[TOTLAMNT] NUMERIC (19,5) NOT NULL,
[COMMENTS] CHAR(500) NOT NULL,
[SOPNUMBE] CHAR(21) NOT NULL,
[INSTLFEE] NUMERIC(19,5) NOT NULL,
[RESRVFEE] NUMERIC(19,5) NOT NULL,
PRIMARY KEY (SOPTYPE, ASSESSNO)
)

CREATE NONCLUSTERED INDEX IDX_CUSTNMBR ON SISC10100(CUSTNMBR ASC)
CREATE NONCLUSTERED INDEX IDX_DOCDATE ON SISC10100(CUSTNMBR, DOCDATE ASC)
CREATE NONCLUSTERED INDEX IDX_CUSTNMBR_ASSESSNO ON SISC10100(CUSTNMBR, ASSESSNO ASC)
--exec sp_columns SISC10100
--exec sp_helpindex sisc10100

GO

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON SISC10100 TO DYNGRP;

GO